### ISSUE TITLE
Transaction history concept

### ISSUE THREAD

**Issue by zpoken** [penumbra-zone/wallet#5]
Now the user cannot view the transaction history on the static site. We need to add this feature. 
The basic concept:

1. Extension view service already scans blocks and saves FVK-affiliated transactions in indexedDB. 

2. Extension view service should pass already decrypted transactions to static site. To do this, you can use the `rpc Transactions`

3. The list of transactions will be displayed with this design. It contains information about the height of the block in which the transaction was found, its hash, and its type
<img width="685" alt="image" src="https://user-images.githubusercontent.com/82594516/230122181-8214d4ef-c438-4a2a-9a29-137c8aecb5da.png">

4. The type of transaction is determined by a specific set of actions in a transaction. The type cannot always be defined, because in fact it is possible to create a transaction with any set of actions. 

5. By clicking on the transaction, you can see its details. In fact, this is a universal `TransactionView -> HTML `view. In addition, we can actually inherit the `TransactionPlan -> HTML` view from the extension 
<img width="394" alt="image" src="https://user-images.githubusercontent.com/82594516/230125410-18d99d33-2224-42a2-82ff-47fbc19211a8.png">

**Comment by hdevalence** [comment]
On (2), we'll probably need https://github.com/penumbra-zone/penumbra/issues/2302
